subarch: sparc
target: stage2
version_stamp: @TIMESTAMP@
rel_type: default
profile: default/linux/sparc/17.0
snapshot: @TIMESTAMP@
source_subpath: default/stage1-sparc-@TIMESTAMP@
compression_mode: pixz
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
