subarch: sparc
target: stage3
version_stamp: @TIMESTAMP@
rel_type: default
profile: default/linux/sparc/17.0
snapshot_treeish: @TREEISH@
source_subpath: default/stage1-sparc-@TIMESTAMP@
compression_mode: pixz
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
binrepo_path: sparc/binpackages/17.0/32
