subarch: sparc
target: stage2
version_stamp: systemd-@TIMESTAMP@
rel_type: default
profile: default/linux/sparc/17.0/systemd
snapshot: @TIMESTAMP@
source_subpath: default/stage1-sparc-systemd-@TIMESTAMP@
compression_mode: pixz
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
