subarch: s390x
version_stamp: @TIMESTAMP@
target: stage2
rel_type: default
profile: default/linux/s390/17.0/s390x
snapshot: @TIMESTAMP@
source_subpath: default/stage1-s390x-@TIMESTAMP@
compression_mode: pixz_x
portage_confdir: @REPO_DIR@/releases/portage/stages
pkgcache_path: /var/tmp/catalyst/packages/default/stage2-s390x
