subarch: s390x
version_stamp: @TIMESTAMP@-systemd
target: stage3
rel_type: default
profile: default/linux/s390/17.0/s390x/systemd
snapshot: @TIMESTAMP@
source_subpath: default/stage1-s390x-systemd-@TIMESTAMP@
compression_mode: pixz
portage_confdir: @REPO_DIR@/releases/portage/stages
pkgcache_path: /var/tmp/catalyst/packages/default/stage3-s390x
