subarch: s390x
version_stamp: systemd-mergedusr-@TIMESTAMP@
target: stage3
rel_type: mergedusr
profile: default/linux/s390/17.0/s390x/systemd/merged-usr
snapshot: @TIMESTAMP@
source_subpath: mergedusr/stage1-s390x-systemd-mergedusr-@TIMESTAMP@
compression_mode: pixz
portage_confdir: @REPO_DIR@/releases/portage/stages
binrepo_path: s390/binpackages/17.0/s390x
