subarch: aarch64_be
version_stamp: systemd-@TIMESTAMP@
target: stage3
rel_type: 23.0-default
profile: default/linux/arm64/23.0/big-endian/systemd
snapshot_treeish: @TIMESTAMP@
source_subpath: 23.0-default/stage1-aarch64_be-systemd-@TIMESTAMP@
compression_mode: pixz
portage_confdir: @REPO_DIR@/releases/portage/stages-qemu
portage_prefix: releng
interpreter: /usr/bin/qemu-aarch64_be
binrepo_path: arm64/binpackages/23.0/aarch64_be
