subarch: ppc64le
target: stage3
version_stamp: musl-hardened-@TIMESTAMP@
rel_type: default
profile: default/linux/ppc64le/17.0/musl/hardened
snapshot: @TIMESTAMP@
source_subpath: default/stage1-ppc64le-musl-hardened-@TIMESTAMP@
compression_mode: pixz_x
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
portage_overlay: /var/db/repos/musl
