subarch: power9le
target: stage3
version_stamp: systemd-usrmerge-@TIMESTAMP@
rel_type: power9le
profile: default/linux/ppc64le/17.0/systemd/merged-usr
snapshot: @TIMESTAMP@
source_subpath: power9le/stage1-power9le-systemd-usrmerge-@TIMESTAMP@
compression_mode: pixz
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
