subarch: power9le
target: stage3
version_stamp: desktop-systemd-@TIMESTAMP@
rel_type: 23.0-default
profile: default/linux/ppc64le/23.0/desktop/systemd
snapshot_treeish: @TREEISH@
source_subpath: 23.0-default/stage1-power9le-systemd-@TIMESTAMP@
compression_mode: pixz
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
binrepo_path: ppc/binpackages/23.0/power9le
