subarch: power9le
target: stage3
version_stamp: musl-hardened-openrc-@TIMESTAMP@
rel_type: 23.0-musl-hardened
profile: default/linux/ppc64le/23.0/musl/hardened
snapshot_treeish: @TIMESTAMP@
source_subpath: 23.0-musl-hardened/stage1-power9le-musl-hardened-openrc-@TIMESTAMP@
compression_mode: pixz
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
binrepo_path: ppc/binpackages/23.0/power9le_musl_hardened
