subarch: ppc64le
target: stage3
version_stamp: systemd-@TIMESTAMP@
rel_type: default
profile: default/linux/ppc64le/17.0/systemd
snapshot_treeish: @TIMESTAMP@
source_subpath: default/stage1-ppc64le-systemd-@TIMESTAMP@
compression_mode: pixz
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
