subarch: power9le
target: stage3
version_stamp: power9-@TIMESTAMP@
rel_type: power9
profile: default/linux/ppc64le/17.0
snapshot: @TIMESTAMP@
source_subpath: default/stage1-ppc64le-@TIMESTAMP@
compression_mode: pixz_x
portage_confdir: @REPO_DIR@/releases/portage/stages
