subarch: power9le
target: stage3
version_stamp: systemd-mergedusr-@TIMESTAMP@
rel_type: power9le-mergedusr
profile: default/linux/ppc64le/17.0/systemd/merged-usr
snapshot: @TIMESTAMP@
source_subpath: power9le-mergedusr/stage1-power9le-systemd-mergedusr-@TIMESTAMP@
compression_mode: pixz
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
binrepo_path: ppc/binpackages/17.0/power9le
