subarch: ppc64le
target: stage3
version_stamp: musl-hardened-openrc-@TIMESTAMP@
rel_type: musl-hardened
profile: default/linux/ppc64le/17.0/musl/hardened
snapshot_treeish: @TREEISH@
source_subpath: musl-hardened/stage1-ppc64le-musl-hardened-openrc-@TIMESTAMP@
compression_mode: pixz
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
binrepo_path: ppc/binpackages/17.0/ppc64le_musl_hardened
