subarch: power9le
target: stage3
version_stamp: musl-hardened-openrc-@TIMESTAMP@
rel_type: power9le-musl-hardened
profile: default/linux/ppc64le/17.0/musl/hardened
snapshot_treeish: @TIMESTAMP@
source_subpath: power9le-musl-hardened/stage1-power9le-musl-hardened-openrc-@TIMESTAMP@
compression_mode: pixz
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
repos: /var/db/repos/musl
