subarch: ppc64le
target: stage3
version_stamp: openrc-@TIMESTAMP@
rel_type: 23.0-default
profile: default/linux/ppc64le/23.0
snapshot: @TIMESTAMP@
source_subpath: 23.0-default/stage1-ppc64le-openrc-@TIMESTAMP@
compression_mode: pixz
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
binrepo_path: ppc/binpackages/23.0/ppc64le
