subarch: ppc64le
target: stage1
version_stamp: musl-hardened-openrc-@TIMESTAMP@
rel_type: 23.0-musl-hardened
profile: default/linux/ppc64le/23.0/musl/hardened
snapshot_treeish: @TREEISH@
source_subpath: 23.0-musl-hardened/stage3-ppc64le-musl-hardened-openrc-latest
chost: powerpc64le-unknown-linux-musl
compression_mode: pixz
update_seed: yes
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
