subarch: power9le
target: stage1
version_stamp: openrc-@TIMESTAMP@
rel_type: 23.0-default
profile: default/linux/ppc64le/23.0
snapshot_treeish: @TIMESTAMP@
source_subpath: 23.0-default/stage3-power9le-openrc-latest
compression_mode: pixz
update_seed: yes
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
