subarch: power9le
target: stage3
version_stamp: openrc-@TIMESTAMP@
rel_type: power9le
profile: default/linux/ppc64le/17.0
snapshot: @TIMESTAMP@
source_subpath: power9le/stage1-power9le-openrc-@TIMESTAMP@
compression_mode: pixz_x
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
