subarch: ia64
version_stamp: systemd-mergedusr-@TIMESTAMP@
target: stage3
rel_type: default
profile: default/linux/ia64/17.0/systemd/merged-usr
snapshot: @TIMESTAMP@
source_subpath: default/stage1-ia64-systemd-mergedusr-@TIMESTAMP@
compression_mode: pixz
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
