subarch: ia64
version_stamp: @TIMESTAMP@
target: stage3
rel_type: default
profile: default/linux/ia64/17.0
snapshot: @TIMESTAMP@
source_subpath: default/stage1-ia64-@TIMESTAMP@
compression_mode: pixz
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
