subarch: i686-ssemath
target: stage3
version_stamp: systemd-@TIMESTAMP@
rel_type: 23.0-default
profile: default/linux/x86/23.0/i686-ssemath/systemd
snapshot_treeish: @TREEISH@
source_subpath: 23.0-default/stage1-i686-ssemath-systemd-@TIMESTAMP@
compression_mode: pixz
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
binrepo_path: x86/binpackages/23.0/i686-ssemath
