subarch: hppa1.1
target: stage2
version_stamp: 2008.0
rel_type: default
profile: default/linux/hppa/17.0
snapshot: 2008.0
source_subpath: default/stage1-hppa1.1-2008.0
portage_confdir: @REPO_DIR@/releases/weekly/portage/stages
pkgcache_path: /var/tmp/catalyst/packages/default/stage2-hppa1.1
