subarch: sparc64
target: stage3
version_stamp: systemd-@TIMESTAMP@
rel_type: 23.0-default
profile: default/linux/sparc/23.0/64ul/systemd
snapshot_treeish: @TREEISH@
source_subpath: 23.0-default/stage1-sparc64-systemd-@TIMESTAMP@
interpreter: /usr/bin/qemu-sparc64
compression_mode: pixz
portage_confdir: @REPO_DIR@/releases/portage/stages-qemu
portage_prefix: releng
binrepo_path: sparc/binpackages/23.0/64
