subarch: hppa2.0
target: stage1
version_stamp: 2008.0
rel_type: default
profile: default/linux/hppa/17.0
snapshot: 2008.0
source_subpath: default/stage3-hppa2.0-latest
update_seed: yes
portage_confdir: @REPO_DIR@/releases/portage/stages
pkgcache_path: /var/tmp/catalyst/packages/default/stage1-hppa2.0
