subarch: hppa2.0
target: stage2
version_stamp: 2008.0
rel_type: default
profile: default/linux/hppa/17.0
snapshot: 2008.0
source_subpath: default/stage1-hppa2.0-2008.0
portage_confdir: @REPO_DIR@/releases/portage/stages
pkgcache_path: /var/tmp/catalyst/packages/default/stage2-hppa2.0
