subarch: arm64
target: stage3
version_stamp: openrc-splitusr-@TIMESTAMP@
rel_type: 23.0-splitusr
profile: default/linux/arm64/23.0/split-usr
snapshot_treeish: @TREEISH@
source_subpath: 23.0-splitusr/stage1-arm64-openrc-splitusr-@TIMESTAMP@.tar.xz
compression_mode: pixz
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
