subarch: arm64
target: stage3
version_stamp: openrc-@TIMESTAMP@
rel_type: default
profile: default/linux/arm64/17.0
snapshot_treeish: @TIMESTAMP@
source_subpath: default/stage1-arm64-openrc-@TIMESTAMP@.tar.xz
compression_mode: pixz
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
