subarch: arm64
target: stage2
version_stamp: @TIMESTAMP@
rel_type: default
profile: default/linux/arm64/17.0
snapshot: @TIMESTAMP@
source_subpath: default/stage1-arm64-@TIMESTAMP@
compression_mode: pixz_x
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
