subarch: armv4tl
version_stamp: @TIMESTAMP@
target: stage2
rel_type: default
profile: default/linux/arm/17.0/armv4t
snapshot: @TIMESTAMP@
source_subpath: default/stage1-armv4tl-@TIMESTAMP@
compression_mode: pixz_x
portage_confdir: @REPO_DIR@/releases/portage/stages-qemu
portage_prefix: releng
interpreter: /usr/bin/qemu-arm
