subarch: ppc
target: stage3
version_stamp: musl-hardened-openrc-@TIMESTAMP@
rel_type: musl-hardened
profile: default/linux/ppc/17.0/musl/hardened
snapshot: @TIMESTAMP@
source_subpath: musl-hardened/stage1-ppc-musl-hardened-openrc-@TIMESTAMP@
compression_mode: pixz_x
portage_confdir: @REPO_DIR@/releases/portage/stages-musl
portage_prefix: releng
repos: /var/db/repos/musl
