subarch: ppc
target: stage3
version_stamp: systemd-@TIMESTAMP@
rel_type: default
profile: default/linux/ppc/17.0/systemd
snapshot: @TIMESTAMP@
source_subpath: default/stage1-ppc-systemd-@TIMESTAMP@
compression_mode: pixz
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
