subarch: ppc
target: stage3
version_stamp: musl-hardened-openrc-@TIMESTAMP@
rel_type: musl-hardened
profile: default/linux/ppc/17.0/musl/hardened
snapshot_treeish: @TIMESTAMP@
source_subpath: musl-hardened/stage1-ppc-musl-hardened-openrc-@TIMESTAMP@
compression_mode: pixz
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
binrepo_path: ppc/binpackages/17.0/ppc_musl_hardened
