subarch: ppc
target: stage3
version_stamp: @TIMESTAMP@
rel_type: default
profile: default/linux/powerpc/ppc32/17.0
snapshot: @TIMESTAMP@
source_subpath: default/stage1-ppc-@TIMESTAMP@
compression_mode: pixz_x
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
