subarch: ppc
target: stage3
version_stamp: systemd-@TIMESTAMP@
rel_type: 23.0-default
profile: default/linux/ppc/23.0/systemd
snapshot_treeish: @TIMESTAMP@
source_subpath: 23.0-default/stage1-ppc-systemd-@TIMESTAMP@
compression_mode: pixz
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
binrepo_path: ppc/binpackages/23.0/ppc
