subarch: ppc64
target: stage3
version_stamp: systemd-mergedusr-@TIMESTAMP@
rel_type: default
profile: default/linux/ppc64/17.0/systemd/merged-usr
snapshot: @TIMESTAMP@
source_subpath: default/stage1-ppc64-systemd-mergedusr-@TIMESTAMP@
compression_mode: pixz
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
