subarch: ppc64
target: stage2
version_stamp: @TIMESTAMP@
rel_type: default
profile: default/linux/powerpc/ppc64/17.0/64bit-userland
snapshot: @TIMESTAMP@
source_subpath: default/stage1-ppc64-@TIMESTAMP@
compression_mode: pixz_x
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
