subarch: ppc64
target: stage3
version_stamp: systemd-@TIMESTAMP@
rel_type: default
profile: default/linux/ppc64/17.0/systemd
snapshot: @TIMESTAMP@
source_subpath: default/stage1-ppc64-systemd-@TIMESTAMP@
compression_mode: pixz_x
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
