subarch: ppc64
target: stage2
version_stamp: 32ul-@TIMESTAMP@
rel_type: default
profile: default/linux/powerpc/ppc64/17.0/32bit-userland
snapshot: @TIMESTAMP@
source_subpath: default/stage1-ppc64-32ul-@TIMESTAMP@
compression_mode: pixz_x
chost: powerpc-unknown-linux-gnu
portage_confdir: @REPO_DIR@/releases/portage/stages
