subarch: i486
target: stage3
version_stamp: openrc-@TIMESTAMP@
rel_type: default
profile: default/linux/x86/17.0
snapshot: @TIMESTAMP@
source_subpath: default/stage1-i486-openrc-@TIMESTAMP@
compression_mode: pixz
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
binrepo_path: x86/binpackages/17.0/i486
