subarch: hppa1.1
target: stage3
version_stamp: openrc-@TIMESTAMP@
rel_type: default
profile: default/linux/hppa/17.0
snapshot: @TIMESTAMP@
source_subpath: default/stage1-hppa1.1-openrc-@TIMESTAMP@
portage_confdir: @REPO_DIR@/releases/portage/stages
interpreter: /usr/bin/qemu-hppa
