subarch: arm64
target: stage3
version_stamp: musl-llvm-openrc-@TIMESTAMP@
rel_type: 23.0-musl-llvm
profile: default/linux/arm64/23.0/musl/llvm
snapshot_treeish: @TREEISH@
source_subpath: 23.0-musl-llvm/stage1-arm64-musl-llvm-openrc-@TIMESTAMP@.tar.xz
compression_mode: pixz
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
binrepo_path: arm64/binpackages/23.0/arm64_musl_llvm
