subarch: arm64
target: stage3
version_stamp: musl-llvm-@TIMESTAMP@
rel_type: musl-llvm
profile: default/linux/arm64/17.0/musl/llvm
snapshot_treeish: @TIMESTAMP@
source_subpath: musl-llvm/stage1-arm64-musl-llvm-@TIMESTAMP@.tar.xz
compression_mode: pixz
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
