subarch: amd64
target: stage3
version_stamp: nomultilib-openrc-@TIMESTAMP@
rel_type: default
profile: default/linux/amd64/17.1/no-multilib
snapshot_treeish: @TIMESTAMP@
source_subpath: default/stage1-amd64-nomultilib-openrc-@TIMESTAMP@
compression_mode: pixz
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
binrepo_path: amd64/binpackages/17.1/x86-64
