subarch: amd64
target: stage3
version_stamp: nomultilib-systemd-@TIMESTAMP@
rel_type: default
profile: default/linux/amd64/17.1/no-multilib/systemd
snapshot_treeish: @TREEISH@
source_subpath: default/stage1-amd64-nomultilib-systemd-@TIMESTAMP@
compression_mode: pixz
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
