subarch: armv7a_hardfp_musl
version_stamp: hardened-openrc-@TIMESTAMP@
target: stage3
rel_type: musl-hardened
profile: default/linux/arm/17.0/musl/armv7a/hardened
snapshot_treeish: @TIMESTAMP@
source_subpath: musl-hardened/stage1-armv7a_hardfp_musl-hardened-openrc-@TIMESTAMP@.tar.xz
compression_mode: pixz
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
binrepo_path: arm/binpackages/17.0/armv7a_hardfp_musl_hardened
