subarch: armv7a_hardfp_musl
version_stamp: hardened-openrc-@TIMESTAMP@
target: stage3
rel_type: musl-hardened
profile: default/linux/arm/17.0/musl/armv7a/hardened
snapshot: @TIMESTAMP@
source_subpath: musl/stage1-armv7a_hardfp_musl-hardened-openrc-@TIMESTAMP@
compression_mode: pixz
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
repos: /root/musl
