subarch: arm64
target: stage3
version_stamp: musl-@TIMESTAMP@
rel_type: musl
profile: default/linux/arm64/17.0/musl
snapshot_treeish: @TREEISH@
source_subpath: musl/stage1-arm64-musl-@TIMESTAMP@.tar.xz
compression_mode: pixz
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
binrepo_path: arm64/binpackages/17.0/arm64_musl
