subarch: alpha
target: stage1
version_stamp: 2008.0
rel_type: default
profile: default/linux/alpha/13.0
snapshot: 2008.0
source_subpath: default/stage3-alpha-latest
update_seed: yes
portage_confdir: /release/releng/releases/weekly/portage/stages
