subarch: armv7a_hardfp
version_stamp: systemd-@TIMESTAMP@
target: stage3
rel_type: default
profile: default/linux/arm/17.0/armv7a/systemd
snapshot: @TIMESTAMP@
source_subpath: default/stage2-armv7a_hardfp-systemd-@TIMESTAMP@
compression_mode: pixz_x
portage_confdir: @REPO_DIR@/releases/portage/stages-qemu
portage_prefix: releng
interpreter: /usr/bin/qemu-arm
