subarch: amd64
target: stage2
version_stamp: hardened-openrc-@TIMESTAMP@
rel_type: hardened
profile: default/linux/amd64/17.1/hardened
snapshot: @TIMESTAMP@
source_subpath: hardened/stage1-amd64-hardened-openrc-@TIMESTAMP@
compression_mode: pixz_x
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
