subarch: amd64
target: stage3
version_stamp: hardened-openrc-@TIMESTAMP@
rel_type: 23.0-hardened
profile: default/linux/amd64/23.0/hardened
snapshot_treeish: @TREEISH@
source_subpath: 23.0-hardened/stage1-amd64-hardened-openrc-@TIMESTAMP@
compression_mode: pixz
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
binrepo_path: amd64/binpackages/23.0/x86-64_hardened
