subarch: amd64
target: stage3
version_stamp: hardened-openrc-@TIMESTAMP@
rel_type: hardened
profile: default/linux/amd64/17.1/hardened
snapshot_treeish: @TREEISH@
source_subpath: hardened/stage1-amd64-hardened-openrc-@TIMESTAMP@
compression_mode: pixz
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
binrepo_path: amd64/binpackages/17.1/x86-64_hardened
