subarch: i686
target: stage2
version_stamp: systemd-@TIMESTAMP@
rel_type: default
profile: default/linux/x86/17.0/systemd
snapshot: @TIMESTAMP@
source_subpath: default/stage1-i686-systemd-@TIMESTAMP@
compression_mode: pixz_x
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
