subarch: i686
target: stage3
version_stamp: systemd-mergedusr-@TIMESTAMP@
rel_type: default
profile: default/linux/x86/17.0/systemd/merged-usr
snapshot: @TIMESTAMP@
source_subpath: default/stage1-i686-systemd-mergedusr-@TIMESTAMP@
compression_mode: pixz
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
