subarch: armv4tl
version_stamp: systemd-mergedusr-@TIMESTAMP@
target: stage3
rel_type: mergedusr
profile: default/linux/arm/17.0/armv4t/systemd/merged-usr
snapshot_treeish: @TREEISH@
source_subpath: mergedusr/stage1-armv4tl-systemd-mergedusr-@TIMESTAMP@.tar.xz
compression_mode: pixz
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
binrepo_path: arm/binpackages/17.0/armv4tl
