subarch: armv7a_hardfp
version_stamp: openrc-@TIMESTAMP@
target: stage3
rel_type: default
profile: default/linux/arm/17.0/armv7a
snapshot_treeish: @TREEISH@
source_subpath: default/stage1-armv7a_hardfp-openrc-@TIMESTAMP@.tar.xz
compression_mode: pixz
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
