subarch: armv7a
version_stamp: systemd-mergedusr-@TIMESTAMP@
target: stage3
rel_type: mergedusr
profile: default/linux/arm/17.0/armv7a/systemd/merged-usr
snapshot_treeish: @TREEISH@
source_subpath: mergedusr/stage1-armv7a-systemd-mergedusr-@TIMESTAMP@.tar.xz
compression_mode: pixz
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
