subarch: armv6j_hardfp
version_stamp: t64-systemd-@TIMESTAMP@
target: stage3
rel_type: 23.0-time64
profile: default/linux/arm/23.0/time64/armv6j_hf/systemd
snapshot_treeish: @TREEISH@
source_subpath: 23.0-time64/stage1-armv6j_hardfp-t64-systemd-@TIMESTAMP@.tar.xz
compression_mode: pixz
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
binrepo_path: arm/binpackages/23.0/armv6j_hf-t64
