subarch: i686
target: stage3
version_stamp: hardened-openrc-@TIMESTAMP@
rel_type: 23.0-hardened
profile: default/linux/x86/23.0/i686/hardened
snapshot_treeish: @TREEISH@
source_subpath: 23.0-hardened/stage1-i686-hardened-openrc-@TIMESTAMP@
compression_mode: pixz
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
binrepo_path: x86/binpackages/23.0/i686_hardened
