subarch: i686
target: stage3
version_stamp: hardened-@TIMESTAMP@
rel_type: hardened
profile: default/linux/x86/17.0/hardened
snapshot: @TIMESTAMP@
source_subpath: hardened/stage2-i686-hardened-@TIMESTAMP@
compression_mode: pixz_x
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
