subarch: i686
target: stage3
version_stamp: hardened-openrc-@TIMESTAMP@
rel_type: hardened
profile: default/linux/x86/17.0/hardened
snapshot: @TIMESTAMP@
source_subpath: hardened/stage1-i686-hardened-openrc-@TIMESTAMP@
compression_mode: pixz
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
binrepo_path: x86/binpackages/17.0/i686_hardened
