subarch: armv6j
version_stamp: systemd-@TIMESTAMP@
target: stage3
rel_type: default
profile: default/linux/arm/17.0/armv6j/systemd
snapshot: @TIMESTAMP@
source_subpath: default/stage1-armv6j-systemd-@TIMESTAMP@.tar.xz
compression_mode: pixz
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
binrepo_path: arm/binpackages/17.0/armv6j
