subarch: armv6j_hardfp
version_stamp: openrc-@TIMESTAMP@
target: stage3
rel_type: 23.0-default
profile: default/linux/arm/23.0/armv6j_hf
snapshot_treeish: @TIMESTAMP@
source_subpath: 23.0-default/stage1-armv6j_hardfp-openrc-@TIMESTAMP@.tar.xz
compression_mode: pixz
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
binrepo_path: arm/binpackages/23.0/armv6j_hf
