subarch: armv6j
version_stamp: systemd-mergedusr-@TIMESTAMP@
target: stage3
rel_type: mergedusr
profile: default/linux/arm/17.0/armv6j/systemd/merged-usr
snapshot: @TIMESTAMP@
source_subpath: mergedusr/stage1-armv6j-systemd-mergedusr-@TIMESTAMP@.tar.xz
compression_mode: pixz
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
