subarch: armv6j_hardfp
version_stamp: systemd-@TIMESTAMP@
target: stage3
rel_type: default
profile: default/linux/arm/17.0/armv6j/systemd
snapshot_treeish: @TIMESTAMP@
source_subpath: default/stage1-armv6j_hardfp-systemd-@TIMESTAMP@.tar.xz
compression_mode: pixz
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
