subarch: armv6j
version_stamp: openrc-@TIMESTAMP@
target: stage3
rel_type: default
profile: default/linux/arm/17.0/armv6j
snapshot_treeish: @TIMESTAMP@
source_subpath: default/stage1-armv6j-openrc-@TIMESTAMP@.tar.xz
compression_mode: pixz
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
