subarch: ppc64
target: stage1
version_stamp: 32ul-2008.0
rel_type: default
profile: default/linux/powerpc/ppc64/13.0/32bit-userland
snapshot: 2008.0
source_subpath: default/stage3-ppc64-32ul-latest
chost: powerpc-unknown-linux-gnu
portage_confdir: /release/releng/releases/weekly/portage/stages
