subarch: armv7a
version_stamp: systemd-@TIMESTAMP@
target: stage2
rel_type: default
profile: default/linux/arm/17.0/armv7a/systemd
snapshot: @TIMESTAMP@
source_subpath: default/stage1-armv7a-systemd-@TIMESTAMP@
compression_mode: pixz_x
portage_confdir: @REPO_DIR@/releases/portage/stages-qemu
portage_prefix: releng
interpreter: /usr/bin/qemu-arm
