subarch: arm64
version_stamp: 2008.0
target: stage2
rel_type: default
profile: default/linux/arm64/17.0
snapshot: current
source_subpath: default/stage1-arm64-2008.0
pkgcache_path: /var/tmp/catalyst/packages/stage2
portage_confdir: @REPO_DIR@/releases/weekly/specs/arm64/portage-confdir
