post_src_install() {
	[[ $PN != musl ]] && return 0

	local LDSO_ARCH=$(basename "${D}"/lib/ld-musl-*.so.1)
	mkdir "${D}"/etc
	cat <<- EOF > "${D}"/etc/${LDSO_ARCH%so.1}path
	/lib
	/usr/lib
	/usr/local/lib
	/usr/lib/opengl/xorg-x11/lib
	/usr/lib/gcc/${CHOST}/4.7.4
	/usr/${CHOST}/lib
	/usr/games/lib
	EOF
}
