subarch: ia64
version_stamp: latest
target: stage1
rel_type: default
profile: default/linux/ia64/17.0
snapshot: latest
source_subpath: default/stage3-ia64-latest
update_seed: yes
portage_confdir: @REPO_DIR@/releases/weekly/portage/stages
