subarch: ia64
version_stamp: latest
target: stage2
rel_type: default
profile: default/linux/ia64/17.0
snapshot: latest
source_subpath: default/stage1-ia64-latest
portage_confdir: @REPO_DIR@/releases/weekly/portage/stages
portage_prefix: releng
