subarch: arm64
target: stage3
version_stamp: llvm-openrc-@TIMESTAMP@
rel_type: llvm
profile: default/linux/arm64/17.0/llvm
snapshot_treeish: @TREEISH@
source_subpath: llvm/stage1-arm64-llvm-openrc-@TIMESTAMP@.tar.xz
compression_mode: pixz
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
binrepo_path: arm64/binpackages/17.0/arm64_llvm
