subarch: amd64
target: stage3
version_stamp: hardened-nomultilib-selinux-openrc-@TIMESTAMP@
rel_type: hardened
profile: default/linux/amd64/17.1/no-multilib/hardened/selinux
snapshot_treeish: @TIMESTAMP@
source_subpath: hardened/stage1-amd64-hardened-nomultilib-selinux-openrc-@TIMESTAMP@
compression_mode: pixz
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
