subarch: x32
target: stage3
version_stamp: openrc-@TIMESTAMP@
rel_type: 23.0-default
profile: default/linux/amd64/23.0/x32
snapshot_treeish: @TREEISH@
source_subpath: 23.0-default/stage1-x32-openrc-@TIMESTAMP@
compression_mode: pixz
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
binrepo_path: amd64/binpackages/23.0/x32
