subarch: x32
target: stage3
version_stamp: systemd-@TIMESTAMP@
rel_type: default
profile: default/linux/amd64/17.0/x32/systemd
snapshot_treeish: @TIMESTAMP@
source_subpath: default/stage1-x32-systemd-@TIMESTAMP@
compression_mode: pixz
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
binrepo_path: amd64/binpackages/17.0/x32
