subarch: x32
target: stage3
version_stamp: systemd-mergedusr-@TIMESTAMP@
rel_type: mergedusr
profile: default/linux/amd64/17.0/x32/systemd/merged-usr
snapshot: @TIMESTAMP@
source_subpath: default/stage1-x32-systemd-mergedusr-@TIMESTAMP@
compression_mode: pixz
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
