subarch: x32
target: stage2
version_stamp: openrc-@TIMESTAMP@
rel_type: default
profile: default/linux/amd64/17.0/x32
snapshot: @TIMESTAMP@
source_subpath: default/stage1-x32-openrc-@TIMESTAMP@
compression_mode: pixz_x
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
