subarch: alpha
target: stage3
version_stamp: openrc-@TIMESTAMP@
rel_type: default
profile: default/linux/alpha/17.0
snapshot_treeish: @TREEISH@
source_subpath: default/stage1-alpha-openrc-@TIMESTAMP@
portage_confdir: @REPO_DIR@/releases/portage/stages-qemu
interpreter: /usr/bin/qemu-alpha
compression_mode: pixz
binrepo_path: alpha/binpackages/17.0/alpha
