subarch: alpha
target: stage3
version_stamp: systemd-mergedusr-@TIMESTAMP@
rel_type: default
profile: default/linux/alpha/17.0/systemd/merged-usr
snapshot: @TIMESTAMP@
source_subpath: default/stage1-alpha-systemd-mergedusr-@TIMESTAMP@
portage_confdir: @REPO_DIR@/releases/portage/stages-qemu
interpreter: /usr/bin/qemu-alpha
compression_mode: pixz
