subarch: alpha
target: stage3
version_stamp: openrc-23.0-@TIMESTAMP@
rel_type: 23.0-default
profile: default/linux/alpha/23.0
snapshot: @TIMESTAMP@
source_subpath: 23.0-default/stage1-alpha-openrc-23.0-@TIMESTAMP@
portage_confdir: @REPO_DIR@/releases/portage/stages-qemu
interpreter: /usr/bin/qemu-alpha
compression_mode: pixz
binrepo_path: alpha/binpackages/23.0/alpha
