subarch: alpha
target: stage3
version_stamp: systemd-@TIMESTAMP@
rel_type: default
profile: default/linux/alpha/17.0/systemd
snapshot: @TIMESTAMP@
source_subpath: default/stage1-alpha-systemd-@TIMESTAMP@
portage_confdir: @REPO_DIR@/releases/portage/stages-qemu
interpreter: /usr/bin/qemu-alpha
compression_mode: pixz
