subarch: armv5tel
version_stamp: systemd-@TIMESTAMP@
target: stage3
rel_type: default
profile: default/linux/arm/17.0/armv5te/systemd
snapshot_treeish: @TIMESTAMP@
source_subpath: default/stage1-armv5tel-systemd-@TIMESTAMP@.tar.xz
compression_mode: pixz
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
