subarch: i686
target: stage3
version_stamp: hardened-t64-systemd-@TIMESTAMP@
rel_type: 23.0-hardened-time64
profile: default/linux/x86/23.0/i686/time64/hardened/systemd
snapshot_treeish: @TREEISH@
source_subpath: 23.0-hardened-time64/stage1-i686-hardened-t64-systemd-@TIMESTAMP@
compression_mode: pixz
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
binrepo_path: x86/binpackages/23.0/i686_hardened-t64
