subarch: ppc
target: stage1
version_stamp: 2008.0
rel_type: default
profile: default/linux/powerpc/ppc32/13.0
snapshot: 2008.0
source_subpath: default/stage3-ppc-latest
update_seed: yes
portage_confdir: /release/releng/releases/weekly/portage/stages
