subarch: amd64
target: stage3
version_stamp: hardened-selinux-openrc-@TIMESTAMP@
rel_type: hardened
profile: default/linux/amd64/17.1/hardened/selinux
snapshot: @TIMESTAMP@
source_subpath: hardened/stage2-amd64-hardened-selinux-openrc-@TIMESTAMP@
compression_mode: pixz_x
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
