subarch: amd64
version_stamp: 11.2
target: livecd-stage1
rel_type: default
profile: default/linux/amd64/10.0/desktop
snapshot: 20110729
source_subpath: default/stage3-amd64-20110728
portage_confdir: /var/svnroot/releng/trunk/releases/11.2/portage/

livecd/use:
        -a52
        -amr
        -dvdnav
        -faac
        -hal
        -mp3
        -mp4
        -mpeg2
        -mpeg4pt2
        -real
        -x264
        -xvid
        X
        accessibility
        alsa
        atm
        avahi
        bindist
        branding
        cairo
        consolekit
        dbus
        eds
        fbcondecor
        gif
        gnome
        gnome
        gnome-keyring
        jpeg
        kde
        libnotify
        livecd
        loop-aes
        mmx
        mng
        nautilus
        networkmanager
        nouveau
        opengl
        png
        policykit
        portaudio
        qt3support
        qt4
        semantic-desktop
        socks5
        sse
        sse2
        tiff
        truetype
        usb
        vino
livecd/packages:
        app-admin/conky
        app-admin/eselect-esd
        app-admin/gkrellm
        app-admin/hddtemp
        app-admin/hwreport
        app-admin/ide-smart
        app-admin/localepurge
        app-admin/passook
        app-admin/pwgen
        app-admin/quickswitch
        app-admin/sudo
        app-admin/superadduser
        app-admin/syslog-ng
        app-admin/sysstat
        app-admin/testdisk
        app-admin/usbview
        app-antivirus/clamav
        app-arch/afio
        app-arch/alien
        app-arch/arc
        app-arch/arj
        app-arch/cabextract
        app-arch/cfv
        app-arch/deb2targz
        app-arch/dump
        app-arch/file-roller
        app-arch/lha
        app-arch/lrzip
        app-arch/lzip
        app-arch/lzop
        app-arch/mscompress
        app-arch/mt-st
        app-arch/ncompress
        app-arch/p7zip
        app-arch/par2cmdline
        app-arch/pbzip2
        app-arch/pigz
        app-arch/sharutils
        app-arch/unace
        app-arch/unarj
        app-arch/unrar
        app-arch/unzip
        app-arch/upx-bin
        app-arch/xarchiver
        app-arch/xz-utils
        app-arch/zip
        app-arch/zoo
        app-backup/dar
        app-backup/duplicity
        app-backup/flexbackup
        app-backup/luckybackup
        app-backup/rdiff-backup
        app-backup/rsnapshot
        app-benchmarks/bonnie++
        app-benchmarks/cpuburn
        app-benchmarks/dbench
        app-benchmarks/httperf
        app-benchmarks/iozone
        app-benchmarks/stress
        app-benchmarks/tiobench
        app-cdr/bin2iso
        app-cdr/ccd2iso
        app-cdr/cdrdao
        app-cdr/cdw
        app-cdr/dvd+rw-tools
        app-cdr/k9copy
        app-cdr/nrg2iso
        app-cdr/xfburn
        app-crypt/aespipe
        app-crypt/aesutil
        app-crypt/gnupg
        app-crypt/gpgme
        app-crypt/hashalot
        app-crypt/johntheripper
        app-crypt/mcrypt
        app-crypt/md5deep
        app-crypt/pinentry
        app-editors/bluefish
        app-editors/emacs
        app-editors/gedit
        app-editors/gvim
        app-editors/hexcurse
        app-editors/hexedit
        app-editors/joe
        app-editors/qemacs
        app-editors/scite
        app-editors/vim
        app-editors/xemacs
        app-editors/zile
        app-forensics/autopsy
        app-forensics/chkrootkit
        app-forensics/magicrescue
        app-forensics/memdump
        app-forensics/sleuthkit
        app-laptop/i8kutils
        app-misc/beep
        app-misc/ckermit
        app-misc/colordiff
        app-misc/dtach
        app-misc/emelfm2
        app-misc/mc
        app-misc/pax-utils
        app-misc/screen
        app-misc/splitvt
        app-misc/symlinks
        app-misc/vlock
        app-misc/wipe
        app-office/abiword
        app-office/dia
        app-office/dia2code
        app-office/eqe
        app-office/gnucash
        app-office/gnumeric
        app-office/grisbi
        app-office/karbon
        app-office/kexi
        app-office/koffice-meta
        app-office/kpresenter
        app-office/kspread
        app-office/kword
        app-office/openoffice
        app-office/orage
        app-office/osmo
        app-office/planner
        app-office/scribus
        app-office/texmaker
        app-pda/gtkpod
        app-portage/gentoolkit
        app-portage/layman
        app-portage/mirrorselect
        app-portage/ufed
        app-shells/bash-completion
        app-shells/gentoo-bashcomp
        app-shells/ksh
        app-shells/tcsh
        app-shells/zsh
        app-shells/zsh-completion
        app-text/a2ps
        app-text/dos2unix
        app-text/epdfview
        app-text/evince
        app-text/hunspell
        app-text/wgetpaste
        dev-dotnet/libgdiplus
        dev-lang/fpc
        dev-libs/libmcs
        dev-libs/liboil
        dev-python/pexpect
        dev-python/py-gnupg
        dev-python/pylibacl
        dev-python/pyparted
        dev-python/pyxattr
        dev-util/anjuta
        dev-util/ccache
        dev-util/devhelp
        dev-util/indent
        dev-util/kdevelop
        dev-util/ltrace
        dev-util/qt-creator
        dev-util/strace
        dev-util/valgrind
        dev-util/yacc
        dev-vcs/cvs
        dev-vcs/giggle
        dev-vcs/git
        dev-vcs/kdesvn
        dev-vcs/qgit
        dev-vcs/subversion
        games-arcade/lbreakout2
        games-simulation/lincity-ng
        games-simulation/simutrans
        gnome-base/gdm
        gnome-base/gnome
        gnome-extra/sensors-applet
        kde-base/kde-meta
        kde-misc/akonadi-googledata
        kde-misc/kcm_gtk
        kde-misc/konq-plugins
        kde-misc/nepomukcontroller
        kde-misc/rsibreak
        kde-misc/yakuake
        mail-client/claws-mail
        mail-client/evolution
        mail-client/sylpheed
        mail-client/thunderbird
        mail-client/trojita
        media-fonts/dejavu
        media-gfx/blender
        media-gfx/digikam
        media-gfx/fbgrab
        media-gfx/feh
        media-gfx/gimp
        media-gfx/gtkam
        media-gfx/inkscape
        media-gfx/sane-frontends
        media-gfx/scrot
        media-gfx/splashutils
        media-gfx/xsane
        media-libs/gst-plugins-bad
        media-libs/gst-plugins-base
        media-libs/gst-plugins-good
        media-libs/gstreamer
        media-libs/schroedinger
        media-plugins/alsa-plugins
        media-plugins/gst-plugins-alsa
        media-plugins/gst-plugins-cdparanoia
        media-plugins/gst-plugins-esd
        media-plugins/gst-plugins-gconf
        media-plugins/gst-plugins-gio
        media-plugins/gst-plugins-jpeg
        media-plugins/gst-plugins-libpng
        media-plugins/gst-plugins-libvisual
        media-plugins/gst-plugins-ogg
        media-plugins/gst-plugins-pango
        media-plugins/gst-plugins-soup
        media-plugins/gst-plugins-speex
        media-plugins/gst-plugins-theora
        media-plugins/gst-plugins-v4l
        media-plugins/gst-plugins-v4l2
        media-plugins/gst-plugins-vorbis
        media-plugins/gst-plugins-x
        media-plugins/gst-plugins-xvideo
        media-sound/alsa-utils
        media-sound/amarok
        media-sound/audacious
        media-sound/audacity
        media-sound/aumix
        media-sound/easytag
        media-sound/gnomeradio
        media-sound/grip
        media-sound/hydrogen
        media-sound/pulseaudio
        media-sound/qmmp
        media-sound/rhythmbox
        media-tv/xbmc
        media-video/gnome-mplayer
        media-video/gxine
        media-video/kaffeine
        media-video/lsdvd
        media-video/mplayer
        media-video/ogle-gui
        media-video/rovclock
        media-video/smplayer
        media-video/vlc
        media-video/xine-ui
        net-analyzer/arping
        net-analyzer/dnstracer
        net-analyzer/ettercap
        net-analyzer/httping
        net-analyzer/ifstat
        net-analyzer/iftop
        net-analyzer/iptraf
        net-analyzer/macchanger
        net-analyzer/netcat
        net-analyzer/ngrep
        net-analyzer/nmap
        net-analyzer/snort
        net-analyzer/tcpdump
        net-analyzer/tcptraceroute
        net-analyzer/traceroute
        net-analyzer/vnstat
        net-analyzer/wireshark
        net-dns/bind-tools
        net-dns/dnsmasq
        net-dns/libidn
        net-fs/nfs-utils
        net-fs/samba
        net-ftp/ftp
        net-ftp/gftp
        net-ftp/ncftp
        net-im/kmess
        net-im/licq
        net-im/pidgin
        net-im/qtwitter
        net-im/ysm
        net-irc/cwirc
        net-irc/irssi
        net-irc/irssi-otr
        net-irc/konversation
        net-irc/ninja
        net-irc/quassel
        net-irc/rhapsody
        net-irc/sic
        net-irc/telepathy-idle
        net-irc/xchat
        net-irc/xchat-xsys
        net-nntp/pan
        net-p2p/bittorrent
        net-p2p/ktorrent
        net-p2p/linuxdcpp
        net-p2p/transmission
        net-print/cups
        net-proxy/dante
        net-proxy/ntlmaps
        net-proxy/tsocks
        rox-base/rox
        sci-chemistry/avogadro
        sys-apps/cciss_vol_status
        sys-apps/chpax
        sys-apps/dmapi
        sys-apps/dmidecode
        sys-apps/ed
        sys-apps/eject
        sys-apps/ethtool
        sys-apps/fbset
        sys-apps/fxload
        sys-apps/gradm
        sys-apps/groff
        sys-apps/hdparm
        sys-apps/hwdata-gentoo
        sys-apps/hwsetup
        sys-apps/ipmitool
        sys-apps/iproute2
        sys-apps/lshw
        sys-apps/memtester
        sys-apps/netplug
        sys-apps/paxctl
        sys-apps/pciutils
        sys-apps/pcmciautils
        sys-apps/pcsc-lite
        sys-apps/pmount
        sys-apps/pv
        sys-apps/readahead-list
        sys-apps/ren
        sys-apps/rename
        sys-apps/rescan-scsi-bus
        sys-apps/sdparm
        sys-apps/setserial
        sys-apps/sg3_utils
        sys-apps/smartmontools
        sys-boot/grub
        sys-boot/lilo
        sys-boot/syslinux
        sys-devel/distcc
        sys-devel/gcc
        sys-devel/gdb
        sys-libs/gpm
        sys-power/acpid
        sys-power/apcupsd
        sys-power/powernowd
        sys-power/powertop
        sys-process/atop
        sys-process/htop
        sys-process/iotop
        sys-process/lsof
        sys-process/vixie-cron
        www-client/arora
        www-client/elinks
        www-client/epiphany-extensions
        www-client/firefox
        www-client/httrack
        www-client/links
        www-client/lynx
        www-client/opera
        www-client/seamonkey
        www-plugins/gecko-mediaplayer
        x11-apps/mesa-progs
        x11-apps/xclock
        x11-apps/xev
        x11-apps/xhost
        x11-apps/xinput
        x11-base/xorg-drivers
        x11-base/xorg-x11
        x11-libs/vte
        x11-misc/cairo-clock
        x11-misc/grsync
        x11-misc/menumaker
        x11-misc/obconf
        x11-misc/xscreensaver
        x11-plugins/pidgin-encryption
        x11-plugins/pidgin-extprefs
        x11-proto/dri2proto
        x11-terms/terminal
        x11-terms/xterm
        x11-themes/gdm-themes-livecd
        x11-themes/gentoo-artwork-livecd
        x11-themes/gnome-colors-themes
        x11-themes/oxygen-gtk
        x11-themes/tango-icon-theme
        x11-themes/xfce4-icon-theme
        x11-wm/enlightenment
        x11-wm/fluxbox
        x11-wm/openbox
        x11-wm/windowmaker
        xfce-base/xfce4-meta
        xfce-extra/thunar-volman
        xfce-extra/xfce4-clipman-plugin
        xfce-extra/xfce4-mixer
        xfce-extra/xfce4-notes-plugin
        xfce-extra/xfce4-places-plugin
        xfce-extra/xfce4-screenshooter
