subarch: i686
target: stage3
version_stamp: musl-@TIMESTAMP@
rel_type: musl
profile: default/linux/x86/17.0/musl
snapshot_treeish: @TREEISH@
source_subpath: musl/stage1-i686-musl-@TIMESTAMP@
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
compression_mode: pixz
