subarch: i686
target: stage3
version_stamp: musl-@TIMESTAMP@
rel_type: 23.0-musl
profile: default/linux/x86/23.0/i686/musl
snapshot_treeish: @TREEISH@
source_subpath: 23.0-musl/stage1-i686-musl-@TIMESTAMP@
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
compression_mode: pixz
binrepo_path: x86/binpackages/23.0/i686_musl
