subarch: m68k
version_stamp: systemd-mergedusr-@TIMESTAMP@
target: stage3
rel_type: mergedusr
profile: default/linux/m68k/17.0/systemd/merged-usr
snapshot_treeish: @TIMESTAMP@
source_subpath: mergedusr/stage1-m68k-systemd-mergedusr-@TIMESTAMP@
compression_mode: pixz
portage_confdir: @REPO_DIR@/releases/portage/stages-qemu
portage_prefix: releng
interpreter: /usr/bin/qemu-m68k
