subarch: m68k
version_stamp: systemd-@TIMESTAMP@
target: stage3
rel_type: 23.0-default
profile: default/linux/m68k/23.0/systemd
snapshot_treeish: @TREEISH@
source_subpath: 23.0-default/stage1-m68k-systemd-@TIMESTAMP@
compression_mode: pixz
portage_confdir: @REPO_DIR@/releases/portage/stages-qemu
portage_prefix: releng
interpreter: /usr/bin/qemu-m68k
binrepo_path: m68k/binpackages/23.0/m68k
