subarch: s390
version_stamp: systemd-@TIMESTAMP@
target: stage3
rel_type: default
profile: default/linux/s390/17.0/systemd
snapshot_treeish: @TIMESTAMP@
source_subpath: default/stage1-s390-systemd-@TIMESTAMP@
compression_mode: pixz
portage_confdir: @REPO_DIR@/releases/portage/stages
pkgcache_path: /var/tmp/catalyst/packages/default/stage3-s390
