subarch: s390
version_stamp: systemd-@TIMESTAMP@
target: stage3
rel_type: 23.0-default
profile: default/linux/s390/23.0/systemd
snapshot_treeish: @TREEISH@
source_subpath: 23.0-default/stage1-s390-systemd-@TIMESTAMP@
compression_mode: pixz
portage_confdir: @REPO_DIR@/releases/portage/stages
binrepo_path: s390/binpackages/23.0/s390
