subarch: hppa2.0
target: stage1
version_stamp: openrc-@TIMESTAMP@
rel_type: default
profile: default/linux/hppa/17.0
snapshot: @TIMESTAMP@
source_subpath: default/stage3-hppa2.0-openrc-latest
update_seed: yes
portage_confdir: @REPO_DIR@/releases/portage/stages
interpreter: /usr/bin/qemu-hppa
