subarch: amd64
target: stage3
version_stamp: openrc-splitusr-@TIMESTAMP@
rel_type: 23.0-splitusr
profile: default/linux/amd64/23.0/split-usr
snapshot_treeish: @TREEISH@
source_subpath: 23.0-splitusr/stage1-amd64-openrc-splitusr-@TIMESTAMP@
compression_mode: pixz
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
