subarch: amd64
target: stage3
version_stamp: desktop-systemd-mergedusr-@TIMESTAMP@
rel_type: mergedusr
profile: default/linux/amd64/17.1/desktop/systemd/merged-usr
snapshot_treeish: @TREEISH@
source_subpath: mergedusr/stage1-amd64-systemd-mergedusr-@TIMESTAMP@
compression_mode: pixz
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
