#!/bin/bash
PORTDIR="/release/trees/portage-auto/"
TMPREPO=$(mktemp)
trap "rm -f $TMPREPO" EXIT
cat >$TMPREPO <<EOF
[DEFAULT]
main-repo = gentoo

[gentoo]
location = $PORTDIR
sync-type = rsync
sync-uri = rsync://rsync.gentoo.org/gentoo-portage
EOF
PORTAGE_REPOSITORIES="$(cat $TMPREPO)" FEATURES="$FEATURES -news" emerge --sync -q
