subarch: mipsel2_softfloat
target: stage3
version_stamp: t64-openrc-@TIMESTAMP@
interpreter: /usr/bin/qemu-mipsel
rel_type: 23.0-time64
profile: default/linux/mips/23.0/time64/mipsel/o32_sf
snapshot_treeish: @TREEISH@
source_subpath: 23.0-time64/stage1-mipsel2_softfloat-t64-openrc-@TIMESTAMP@
compression_mode: pixz
decompressor_search_order: xz
portage_confdir: @REPO_DIR@/releases/portage/stages-qemu
portage_prefix: releng
binrepo_path: mips/binpackages/23.0/mipsel2_o32_sf-t64
