subarch: hppa1.1
target: stage3
version_stamp: systemd-@TIMESTAMP@
rel_type: default
profile: default/linux/hppa/17.0/systemd
snapshot: @TIMESTAMP@
source_subpath: default/stage1-hppa1.1-systemd-@TIMESTAMP@
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
pkgcache_path: /var/tmp/catalyst/packages/default/stage3-hppa1.1
