subarch: hppa1.1
target: stage1
version_stamp: openrc-@TIMESTAMP@
rel_type: default
profile: default/linux/hppa/17.0
snapshot: @TIMESTAMP@
source_subpath: default/stage3-hppa1.1-openrc-latest
update_seed: yes
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
pkgcache_path: /var/tmp/catalyst/packages/default/stage1-hppa1.1
