subarch: armv7a_hardfp_musl
version_stamp: openrc-@TIMESTAMP@
target: stage3
rel_type: musl
profile: default/linux/arm/17.0/musl/armv7a
snapshot_treeish: @TREEISH@
source_subpath: musl/stage1-armv7a_hardfp_musl-openrc-@TIMESTAMP@.tar.xz
compression_mode: pixz
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
binrepo_path: arm/binpackages/17.0/armv7a_hardfp_musl
