subarch: armv7a_hardfp_musl
version_stamp: openrc-@TIMESTAMP@
target: stage3
rel_type: musl
profile: default/linux/arm/17.0/musl/armv7a
snapshot: @TIMESTAMP@
source_subpath: musl/stage1-armv7a_hardfp_musl-openrc-@TIMESTAMP@
compression_mode: pixz
portage_confdir: @REPO_DIR@/releases/portage/stages-musl
portage_prefix: releng
repos: /root/musl
