subarch: arm64
target: stage3
version_stamp: musl-hardened-@TIMESTAMP@
rel_type: 23.0-musl-hardened
profile: default/linux/arm64/23.0/musl/hardened
snapshot_treeish: @TREEISH@
source_subpath: 23.0-musl-hardened/stage1-arm64-musl-hardened-@TIMESTAMP@.tar.xz
compression_mode: pixz
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
binrepo_path: arm64/binpackages/23.0/arm64_musl_hardened
