subarch: alpha
target: stage1
version_stamp: latest
rel_type: default
profile: default/linux/alpha/17.0
snapshot: latest
source_subpath: default/stage3-alpha-latest
update_seed: yes
portage_confdir: @REPO_DIR@/releases/portage/stages
