subarch: mips2_softfloat
target: stage3
version_stamp: openrc-@TIMESTAMP@
interpreter: /usr/bin/qemu-mips
rel_type: 23.0-default
profile: default/linux/mips/23.0/o32_sf
snapshot_treeish: @TREEISH@
source_subpath: 23.0-default/stage1-mips2_softfloat-openrc-@TIMESTAMP@
compression_mode: pixz
decompressor_search_order: xz
portage_confdir: @REPO_DIR@/releases/portage/stages-qemu
portage_prefix: releng
binrepo_path: mips/binpackages/23.0/mips2_o32_sf
