subarch: mipsel2_softfloat
target: stage3
version_stamp: systemd-@TIMESTAMP@
interpreter: /usr/bin/qemu-mipsel
rel_type: 23.0-default
profile: default/linux/mips/23.0/mipsel/o32_sf/systemd
snapshot_treeish: @TREEISH@
source_subpath: 23.0-default/stage1-mipsel2_softfloat-systemd-@TIMESTAMP@
compression_mode: pixz
decompressor_search_order: xz
portage_confdir: @REPO_DIR@/releases/portage/stages-qemu
portage_prefix: releng
binrepo_path: mips/binpackages/23.0/mipsel2_o32_sf
