subarch: amd64
target: stage3
version_stamp: musl-hardened-@TIMESTAMP@
rel_type: musl-hardened
profile: default/linux/amd64/17.0/musl/hardened
snapshot: @TIMESTAMP@
source_subpath: musl-hardened/stage1-amd64-musl-hardened-@TIMESTAMP@
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
compression_mode: pixz
binrepo_path: amd64/binpackages/17.1/x86-64_musl_hardened
