subarch: ppc
target: stage3
version_stamp: t64-openrc-@TIMESTAMP@
rel_type: 23.0-time64
profile: default/linux/ppc/23.0/time64
snapshot_treeish: @TREEISH@
source_subpath: 23.0-time64/stage1-ppc-t64-openrc-@TIMESTAMP@
compression_mode: pixz
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
binrepo_path: ppc/binpackages/23.0/ppc-t64
