subarch: amd64
target: stage2
version_stamp: musl-@TIMESTAMP@
rel_type: musl
profile: default/linux/amd64/17.0/musl
snapshot: @TIMESTAMP@
source_subpath: musl/stage1-amd64-musl-@TIMESTAMP@
chost: x86_64-gentoo-linux-musl
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_overlay: /root/musl
portage_prefix: releng
compression_mode: pixz
