subarch: amd64
target: stage3
version_stamp: musl-@TIMESTAMP@
rel_type: musl
profile: default/linux/amd64/17.0/musl
snapshot_treeish: @TREEISH@
source_subpath: musl/stage1-amd64-musl-@TIMESTAMP@
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
compression_mode: pixz
