subarch: amd64
target: stage3
version_stamp: musl-openrc-@TIMESTAMP@
rel_type: 23.0-musl
profile: default/linux/amd64/23.0/musl
snapshot_treeish: @TREEISH@
source_subpath: 23.0-musl/stage1-amd64-musl-openrc-@TIMESTAMP@
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
compression_mode: pixz
binrepo_path: amd64/binpackages/23.0/x86-64_musl
