subarch: amd64
target: stage3
version_stamp: musl-@TIMESTAMP@
rel_type: musl
profile: default/linux/amd64/17.0/musl
snapshot: @TIMESTAMP@
source_subpath: musl/stage2-amd64-musl-@TIMESTAMP@
portage_confdir: @REPO_DIR@/releases/portage/stages-musl
portage_overlay: /root/musl
portage_prefix: releng
compression_mode: pixz
