subarch: sparc
target: stage3
version_stamp: openrc-@TIMESTAMP@
rel_type: 23.0-default
profile: default/linux/sparc/23.0
snapshot_treeish: @TREEISH@
source_subpath: 23.0-default/stage1-sparc-openrc-@TIMESTAMP@
compression_mode: pixz
portage_confdir: @REPO_DIR@/releases/portage/stages
portage_prefix: releng
binrepo_path: sparc/binpackages/23.0/32
